In [1]:
import math
import numpy as np
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import metrics

# Display plots in the notebook
%matplotlib inline

# Plotting parameters 
plt.rcParams['figure.figsize'] = (10, 7)
plt.rcParams['font.size'] = 12

In [10]:
# load files for training
fileL1 = 'http://localhost:8888/tree/data/Node1.csv'
fileL2 = 'http://localhost:8888/tree/data/Node2.csv'
fileL3 = 'http://localhost:8888/tree/data/Node3.csv'
fileL4 = 'http://localhost:8888/tree/data/Node4.csv'

df1 = pd.read_csv(fileL1, header=0, na_filter=False)
df2 = pd.read_csv(fileL2, header=0, na_filter=False)
df3 = pd.read_csv(fileL3, header=0, na_filter=False)
df4 = pd.read_csv(fileL4, header=0, na_filter=False)  

In [11]:
dflist = [df1, df2, df3, df4]
drop_cols = ['PERIOD', 'NODE1', 'NODE2', 'NODE3', 'NODE4']

df1 = df1.drop(drop_cols, axis=1)
df2 = df2.drop(drop_cols, axis=1)
df3 = df3.drop(drop_cols, axis=1)
df4 = df4.drop(drop_cols, axis=1)

In [12]:
def train_test_rmse(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)
    linreg = LinearRegression()
    linreg.fit(X_train, y_train)
    y_pred = linreg.predict(X_test)
    return np.sqrt(mean_squared_error(y_test, y_pred))

In [17]:
print train_test_rmse(df1.drop('DIST4', axis=1), df1.DIST4)
print train_test_rmse(df2.drop('DIST4', axis=1), df2.DIST4)
print train_test_rmse(df3.drop('DIST4', axis=1), df3.DIST4)

3.5527136788e-15
1.25607396695e-15
0.0


In [27]:
# load test sets
fileT1 = 'http://localhost:8888/tree/data/Node1_test.csv'
fileT2 = 'http://localhost:8888/tree/data/Node2_test.csv'
fileT3 = 'http://localhost:8888/tree/data/Node3_test.csv'

T1 = pd.read_csv(fileT1, header=0, na_filter=False)
T2 = pd.read_csv(fileT2, header=0, na_filter=False)
T3 = pd.read_csv(fileT3, header=0, na_filter=False) 

T1 = T1.drop(drop_cols, axis=1)
T2 = T2.drop(drop_cols, axis=1)
T3 = T3.drop(drop_cols, axis=1)

In [28]:
T1

LAT1        LON1      LAT2        LON2        MA2   DIST2      LAT3  \
0  1.351944  103.765833  1.423272  103.844975 -19.750000  11.848  1.359603   
1  1.351944  103.765833  1.425059  103.849078 -21.869565  12.190  1.364013   
2  1.351944  103.765833  1.424709  103.857244 -23.136364  12.870  1.371274   
3  1.351944  103.765833  1.424709  103.857244 -23.136364  12.870  1.371274   

         LON3    MA3  DIST3      LAT4        LON4       MA4  DIST4  
0  103.843286 -1.250  8.619  1.385351  103.745053  9.351852  4.376  
1  103.844911 -5.625  8.870  1.390096  103.745582  3.290909   4.95  
2  103.844609 -7.000  9.020  1.400050  103.748157  1.545455   5.72  
3  103.844609 -7.000  9.020  1.400050  103.748157  0.100000

In [24]:
def dist_predictor(X, y, test):
    linreg = LinearRegression()
    linreg.fit(X, y)
    y_pred = linreg.predict(test)
    return y_pred

In [33]:
print dist_predictor(df1.drop('DIST4', axis=1), df1.DIST4, T1.drop('DIST4', axis=1))
print dist_predictor(df2.drop('DIST4', axis=1), df2.DIST4, T2.drop('DIST4', axis=1))
print dist_predictor(df3.drop('DIST4', axis=1), df3.DIST4, T3.drop('DIST4', axis=1))

[ 4.376       4.95        5.72        5.55303393]
[ 11.885       12.148       12.436       12.46218968]
[ 11.293       11.42        11.193       11.29904996]
